### ISSUE TITLE
missing disable props

### ISSUE THREAD

**Issue by Eth3rnit3** [LarvenLLC/react-custom-checkbox#1]
Hi, thanks for your works!

Is possible to add a `disabled` props to make checkbox unclickable ?

thanks!

**Comment by BossBele** [comment]
@Eth3rnit3 Yes, it is possible. Would you love to contribute by forking the repo, adding the prop and creating a pull request? If not, then I will do it.

Thank you!

**Comment by BossBele** [comment]
@Eth3rnit3 `disabled` prop added on `version 1.0.5`

The prop will have some visual effect on the checkbox (cursor: "not-allowed") which can be edited. But it will also restrict the change of checkbox state (not editable).

**Comment by Eth3rnit3** [comment]
Sorry for the response time, thank you very much!

**Comment by BossBele** [comment]
> Sorry for the response time, thank you very much!

@Eth3rnit3  You're welcome
