### ISSUE TITLE
peer react@"^16.0.0" from react-custom-checkbox@1.0.7

### ISSUE THREAD

**Issue by sandeepkundu4344** [LarvenLLC/react-custom-checkbox#2]
`npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-custom-checkbox@1.0.7
npm ERR! node_modules/react-custom-checkbox
npm ERR!   react-custom-checkbox@"^1.0.7" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/apple/.npm/eresolve-report.txt for a full report.

`
<img width="606" alt="Screenshot 2021-05-15 at 8 34 08 PM" src="https://user-images.githubusercontent.com/8801971/118366080-ea0afd80-b5bc-11eb-98e3-ae74155cdc1a.png">

**Comment by BossBele** [comment]
@sandeepkundu4344 Thank you for reporting the issue. The package seems incompatible with react v17. You may contribute by upgrading the package and submitting a PR. Otherwise, I shall fix it.

**Comment by BossBele** [comment]
For now, install using `--legacy-peer-deps`: `npm install react-custom-checkbox --legacy-peer-deps`

**Comment by BossBele** [comment]
Upgraded package to react 17

**Comment by entozoon** [comment]
Same thing happening again for React 18

**Comment by BossBele** [comment]
@entozoon Sorry for having this recurring error, it is now resolved with version `3.0.0`
