### ISSUE TITLE
TabIndex support

### ISSUE THREAD

**Issue by austinwilcox** [LarvenLLC/react-custom-checkbox#3]
Currently trying to use tabIndex on this, and I'm having no luck. Is there something I'm missing?

**Comment by austinwilcox** [comment]
Currently I am having to hide a checkbox and use that to control the state variable for the checkbox. Here's an example of what I have.
```
<input tabIndex={5} type="checkbox" style={{ opacity: '0', position: 'absolute' }} checked={isChecked} onClick={() => { setIsChecked(!isChecked)}} />
```

**Comment by BossBele** [comment]
Added tabIndex functionality. Checkboxes can now be focused and toggled using Spacebar and Enter key

See Example Website: https://github.larven.co.tz/react-custom-checkbox/
