### ISSUE TITLE
typescript compatibility

### ISSUE THREAD

**Issue by roborobs1023** [LarvenLLC/react-custom-checkbox#9]
Do you have a version that is typescript compatible

**Comment by BossBele** [comment]
Hello @roborobs1023 
We currently do not have a typescript-compatible version, however, we wish to soon make our package compatible. Do you have the bandwidth to help with this?

**Comment by BossBele** [comment]
The pull request adds TypeScript typings in the library (v3.1.5) for the Checkbox and Switch components. The library is Typescript compatible.
